eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
name:
  value: alibou
spring:
  cloud:
    config:
<<<<<<< HEAD
      override-system-properties: false

management:
  tracing:
    sampling:
      probability: 1.0
=======
      override-system-properties: false
>>>>>>> 0c60b97 (config server)
